### PR TITLE
Remove variable length arrays to support MSVC

### PR DESCRIPTION
**Pull request by woodrowbarlow**
@tresf has determined that the use of VLAs in two locations is the only
thing preventing compilation under MSVC. Replacing them with something
else will allow support for MSVC.

This would address issue #2.

### CODE REVIEW

**Comment by therealchalz** [comment]
It's been a while, but I think we'd want `byteCount * sizeof(jbyte)` instead of `byteCount * sizeof(jbyte *)` since we're making an array of jbytes, not an array of pointers to jbytes.  `sizeof(jbyte *)` would likely be 4 or 8 bytes depending on the platform.

**Comment by woodrowbarlow** [comment]
@therealchalz is correct, i made a mistake.

**Comment by tresf** [comment]
Thanks!  In lieu of #9, I'm going to hold off on merging this until we have a baseline that works.  Currently there's something different from @scream3r's binary to ours that makes it not run on older Windows OSs.  This may be an issue with newer `mingw` versions, or it may be something in our build flags.

**Comment by tresf** [comment]
Added `/MT` flag to copy `-static-libgcc -static-libstdc++` options on gcc and disabled optimization on MSVC to be consistent with mingw.

**Pull request merged**
